name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'adopt'
      - name: Generate Keystore
        run: |
              cd/home/runner/work/TVNucleon
              keytool -genkey -v -keystore TVBoxOSC.jks -alias TVBoxOSC -keyalg RSA -keysize 2048 -validity 10000 -storepass TVBoxOSC -keypass TVBoxOSC -dname "CN=John Doe, OU=Engineering Department, O=ABC Company, L=San Francisco, ST=California, C=US"
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          PATH: /usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH
    
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
